### ISSUE TITLE
Status Update

### ISSUE THREAD

**Issue by Greg-Hitchon** [mwiedemeyer/spfx-router-issue-sample#1]
Hello,

Running into the same problem and just wondered if you had any additional info on [this issue](https://github.com/SharePoint/sp-dev-docs/issues/3624)?

Thanks for bringing the issue to Microsoft's attention, definitely a bit of a pain!

**Comment by mwiedemeyer** [comment]
No sorry. We have accepted it as it is.

**Comment by stefan-li-avepoint** [comment]
Has this problem been fixed by Microsoft? In which version?

**Comment by mwiedemeyer** [comment]
I really don't know. I'm working on different topics since 2 years.
